unleash:
  integration: true
  output-statuses: "lc"
  timeout-coefficient: 3
  exclude-files:
    - sdk/api/
    - sdk/auth/inmemory.go
    - sdk/dss/inmemory.go
    - sdk/peer/inmemory.go
    - test/

mutants:
  invert-assignments:
    enabled: true
  invert-bitwise:
    enabled: true
  invert-bwassign:
    enabled: true
  invert-logical:
    enabled: true
  invert-loopctrl:
    enabled: true
  remove-self-assignments:
    enabled: true
