services:
  openuss:
    build: .
    image: openuss:local
    container_name: openuss
    hostname: openuss.uss5.localutm
    environment:
      DSS_BASE_URL: ${DSS_BASE_URL:-http://dss1.uss1.localutm}
      OAUTH_ENDPOINT: ${OAUTH_ENDPOINT:-http://oauth.authority.localutm:8085/token}
      OAUTH_SUB: ${OAUTH_SUB:-uss5}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/flight_planning/v1/status"]
      interval: 2s
      retries: 15
      start_period: 1s
    networks:
      - interop_ecosystem_network

networks:
  interop_ecosystem_network:
    external: true
